export const Groceries = [
    { key: '1', grocery: 'Milk' },
    { key: '2', grocery: 'Salmon' },
    { key: '3', grocery: 'Bread' },
    { key: '4', grocery: 'Meat' },
    { key: '5', grocery: 'Seafood' },
    { key: '6', grocery: 'Pasta' },
    { key: '7', grocery: 'Rice' },
    { key: '8', grocery: 'Oils' },
    { key: '9', grocery: 'Sauces' },
    { key: '10', grocery: 'Salad Dressings' },
    { key: '11', grocery: 'Condiments' },
    { key: '12', grocery: 'Cereals ' },
    { key: '13', grocery: 'Breakfast Foods' },
    { key: '14', grocery: 'Soups' },
    { key: '15', grocery: 'Canned Goods' },
    { key: '16', grocery: 'Frozen Foods' },
    { key: '17', grocery: 'Dairy' },
    { key: '18', grocery: 'Cheese' },
    { key: '19', grocery: 'Eggs' },
    { key: '20', grocery: 'Tomato sauce' },
    { key: '21', grocery: 'Mustard' },
    { key: '22', grocery: 'Barbecue sauce' },
    { key: '23', grocery: 'Red-wine vinegar' },
    { key: '24', grocery: 'Salsa' },
    { key: '25', grocery: 'Jarred capers ' },
    { key: '26', grocery: 'olives' },
    { key: '27', grocery: 'Hot pepper sauce' },
    { key: '28', grocery: 'Tuna ' },
    { key: '29', grocery: 'soymilk' },
    { key: '30', grocery: 'yogurt' },
    { key: '31', grocery: 'Firm tofu' },
    { key: '32', grocery: 'Butter ' },
    { key: '33', grocery: 'apricots' },
    { key: '34', grocery: 'figs' },
    { key: '35', grocery: 'prunes' },
    { key: '36', grocery: 'raisins' },
    { key: '37', grocery: 'cranberries' },
    { key: '38', grocery: 'almonds' },
    { key: '39', grocery: 'cashews' },
    { key: '40', grocery: 'walnuts' },
    { key: '41', grocery: 'peanuts' },
    { key: '42', grocery: 'pecans' },
    { key: '43', grocery: 'pistachios ' },
    { key: '44', grocery: 'sunflower seeds' },
    { key: '45', grocery: 'sesame seeds ' },
    { key: '46', grocery: 'flaxseeds' },
    { key: '47', grocery: 'Peanut butter' },
    { key: '48', grocery: 'almond' },
    { key: '49', grocery: 'Honey' },
    { key: '50', grocery: 'pickle' },
]